[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.14"
hex = "0.4.3"
serde = "1.0.160"
serde_bytes = "0.11.9"
